misc:
  run_mode: test # Mode to run the network in
  num_points: 99999 # Number of points
  use_gpu: True # If GPU should be used or not

data:
  dataset: StereoKITTI_ME # Name of the dataset [StereoKITTI_ME, FlyingThings3D_ME, SemanticKITTI_ME, LidarKITTI_ME, WaymoOpen_ME]
  root: ../stereo_kitti # Path to the data
  remove_ground: True # Remove ground by simple thresholding of the height coordinate
  augment_data: False # Augment the data by random rotation and translation
  only_near_points: True # Only consider near points (less than 35m away) [Used in all scene flow algorithms]
  only_front_points: False

test:
  batch_size: 1 # Test batch size
  num_workers: 0 # Num of workers to use for the test data set
  
hyperparameters:
  sigmoid_slope: 8
  epsilon: .01
  heading_loss_coeff: 5000
  angle_loss_coeff: .1
  mass_loss_coeff: .005
  dim_loss_coeff: 150
  prune_threshold: 500
  confidence_threshold: .85
  seg_threshold: .01
  k_normals: 50
  print_loss: False
  lr: .015 #.015, .05
  epochs: 500 #500, 150